# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: My sample book
author: The Jupyter Book Community
logo: UKCEH_EDST_Logo.png

# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
# Auto-exclude files not in the toc
only_build_toc_files        : true

#######################################################################################
# Execution settings
execute:
  execute_notebooks: off # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache: ""    # A path to the jupyter cache that will be used to store execution artifacts. Defaults to `_build/.jupyter_cache/`
  exclude_patterns: ['*.ipynb']  # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
  timeout: -1 # The maximum time (in seconds) each notebook cell is allowed to run.
  run_in_temp               : false # If `True`, then a temporary directory will be created and used as the command working directory (cwd),otherwise the notebook's parent directory will be the cwd.
  allow_errors              : false # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.
  stderr_output             : show  # One of 'show', 'remove', 'remove-warn', 'warn', 'error', 'severe'
  only_build_toc_files: true

# # Force re-execution of notebooks on each build.
# # See https://jupyterbook.org/content/execute.html
# execute:
#   execute_notebooks: force

# nb_execution_timeout = 60

launch_buttons:
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
  # colab_url: "https://colab.research.google.com"
  colab_url: "https://deepnote.com"


# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/Jez-Carter/UKCEH_Data_Science_Book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  config:
    nb_custom_formats:
        .Rmd:
            - jupytext.reads
            - fmt: Rmd
    exclude_patterns: [
      "**/renv/**",
      "**/skeleton.*"
    ]

# parse:
#   myst_enable_extensions:
#     # don't forget to list any other extensions you want enabled,
#     # including those that are enabled by default! See here: https://jupyterbook.org/en/stable/customize/config.html
#     - html_image
#     - mathjax


# # Launch button settings
# launch_buttons:
#   notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
#   binderhub_url             : false # The URL of the BinderHub (e.g., https://mybinder.org or https://binder.pangeo.io, https://aws-uswest2-binder.pangeo.io)
#   jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
#   thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
#   colab_url                 : "" # The URL of Google Colab (https://colab.research.google.com)

# html:
#   use_issues_button: true
#   use_repository_button: true
#   use_edit_page_button: true  # Whether to add an "Suggest edit" button to pages. If `true`, repository information in repository: must be filled in
#   google_analytics_id: "G-3E20PWD938"

# repository:
#   url: https://github.com/alan-turing-institute/environmental-ds-book # Online location of your book
#   path_to_book: book  # Optional path to your book, relative to the repository root
#   branch: master  # Which branch of the repository should be used when creating links (optional)
